---
apiVersion: v1
kind: Service
metadata:
  name: svc-eureka-app
  namespace: group1-team2
spec:
  selector:
    app: d-group1-team2-eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30208
  type: NodePort