# springboot-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-eureka-app
  namespace: group1-team2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d-group1-team2-eureka
  template:
    metadata:
      labels:
        app: d-group1-team2-eureka
    spec:
      containers:
      - name: container-eureka-app
        image: k8s-vga-worker1:5000/group1-team2-eureka-app
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 8761