# springboot-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-gateway-app
  namespace: group1-team2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d-group1-team2-gateway
  template:
    metadata:
      labels:
        app: d-group1-team2-gateway
    spec:
      containers:
      - name: container-gateway-app
        image: k8s-vga-worker1:5000/group1-team2-gateway-app
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 9000