---
apiVersion: v1
kind: Service
metadata:
  name: svc-gateway-app
  namespace: group1-team2
spec:
  selector:
    app: d-group1-team2-gateway
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30220
  type: NodePort