spring:
  application:
    name: configserver
  profiles:
    # active: native # target: file directory
    active: local
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config" // resource 폴더 아래의 config 폴더
          # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          # uri: "file:///Users//eazybytes//Documents//config"
          # <- git 으로 init 된 디렉토리 (로컬 git 디렉토리). git init -> git add . -> git commit -m "commit message" -> git branch -M main
          uri: https://github.com/newtein80/msa_config_files.git
          default-label: main # branch name
          # search-paths: "{application}"
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: svc-rabbitmq-app
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8071

# logging 설정
logging:
  config: classpath:log4j2.xml
# logging.pattern.console=%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){green} %highlight([%-5level]) %clr(%logger{1.}){faint} %clr(:){red} %clr(%m){cyan}%n
# logging.pattern.conversion.class=ch.qos.logback.classic.pattern.ClassNameOnlyConverter