apiVersion: v1
kind: PersistentVolume
metadata:
  name: park-mysql-pv
  labels:
    app: park-mysql # pvc 에서 매칭해야 할 이름
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/root/park/mysql"
