apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: park-mysql-pvc # deployment 에서 매칭해야 할 이름
  namespace: park1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      app: park-mysql # pv 의 metadata.labels.app
