apiVersion: v1
kind: Service
metadata:
  name: park-mysql-service
  namespace: park1
spec:
  type: NodePort
  selector:
    app: deploy-park-mysql # deployment 의 spec.selector.matchLabels.app, spec.template.metadata.labels.app
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 # 서비스가 사용하는 포트
    nodePort: 30306 # 외부와 연결되어야 하는 포트
