apiVersion: v1
kind: PersistentVolume # PV를 정의하는 Kubernetes 리소스
metadata:
  name: group1-team2-app-log-pv # PV의 이름 (PVC에서 매칭할 수도 있음)
  labels:
    app: group1-team2-app # PVC에서 특정 PV를 선택할 때 사용할 수 있는 라벨
spec:
  capacity:
    storage: 1Gi # PV의 전체 저장 용량 (1GiB)
  accessModes:
    - ReadWriteOnce # 하나의 노드에서만 읽기/쓰기가 가능
  persistentVolumeReclaimPolicy: Retain # PVC 삭제 시 데이터 유지 (재사용 가능)
  hostPath:
    path: "/home/eva/user/group1/team2/spring_app/logs" # 이 PV가 실제로 마운트될 호스트의 디렉토리 경로