apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: group1-team2-app-log-pvc
  namespace: group1-team2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi