apiVersion: v1
kind: Service
metadata:
  name: group1-team2-app-service
  namespace: group1-team2
spec:
  type: NodePort
  selector:
    app: group1-team2-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30207