---
apiVersion: v1
kind: Service
metadata:
  name: svc-configserver-app
  namespace: group1-team2
spec:
  selector:
    app: d-group1-team2-configserver
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
      nodePort: 30209
  type: NodePort