apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-park-eurekaserver
  namespace: park1
spec:
  replicas: 1
  selector:
    matchLabels:
      # service 에서 매칭해야 할 이름
      app: deploy-park-eurekaserver
  template:
    metadata:
      labels:
        # service 에서 매칭해야 할 이름
        app: deploy-park-eurekaserver
    spec:
      containers:
      - name: container-park-eurekaserver
        # docker build -t 192.168.205.10:5000/eurekaserver:latest .
        # docker push 192.168.205.10:5000/eurekaserver:latest 
        image: 192.168.205.10:5000/eurekaserver:latest 
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  # container 내부 pod 간의 연결 host ex) svc-park-eurekaserver:8761
  name: svc-park-eurekaserver
  namespace: park1
spec:
  selector:
    # Deployment 의 아래 속성과 동일해야 한다.
    # spec.selector.matchLabels.app
    # spec.template.metadata.labels.app
    app: deploy-park-eurekaserver
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30002
  type: NodePort